included: # paths to include during linting. `--path` is ignored if present.
  - CommonCodePhone
  - CommonCodeWatch
  - OctoPrint
  - OctoPrintWatch
  - OctoPrintWatch Extension
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
